name: inventory-management-system

runtime: container

container:
  dockerfile: Dockerfile
  port: 8000

# This section injects the secrets into process.env
env:
  - name: DATABRICKS_HOST
    value: "https://dbc-9cecc357-eef2.cloud.databricks.com"
  - name: DATABRICKS_TOKEN
    valueFrom: databricks_token_secret
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: warehouse_id_secret
  - name: NODE_ENV
    value: "production"

# This section defines where the values come from
resources:
  - name: databricks_token_secret
    type: secret
    secret:
      scope: inventory-scope
      key: DATABRICKS_TOKEN
  - name: warehouse_id_secret
    type: secret
    secret:
      scope: inventory-scope
      key: DATABRICKS_WAREHOUSE_ID
